name: dart2native_cross
version: 0.0.1
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/aot

# Add the bin/dart2native_cross.dart script to the scripts pub installs.
executables:
  dart2native_cross:

dependencies:
  meta: ^1.1.8
  path: ^1.6.4
  args: ^1.5.2

# dev_dependencies:

